name: CI
on:
  pull_request:
    types:
      - 'labeled'
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "${{ github.event.label.name == 'PR status: code ready' }}"
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.10
      - run: bun install -y
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
      - name: Setup OKTA Testing Environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TESTING_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Vercel CLI
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: bun add --global vercel@latest
      - name: Setup Canvas
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: npm rebuild canvas
      - uses: nrwl/nx-set-shas@v4
      - run: git branch --track main origin/main
      - name: Run lint on affected projects
        run: bunx nx affected -t lint --parallel=5 --output-style=stream-without-prefixes

  test:
    runs-on: ubuntu-latest
    if: "${{ github.event.label.name == 'PR status: code ready' }}"
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.10
      - run: bun install -y
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
      - name: Setup OKTA Testing Environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TESTING_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Vercel CLI
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: bun add --global vercel@latest
      - name: Setup Canvas
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: npm rebuild canvas
      - uses: nrwl/nx-set-shas@v4
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - name: Run test on affected projects
        run: bunx nx affected -t test --parallel=5 --output-style=stream-without-prefixes

  build:
    runs-on: ubuntu-latest
    if: "${{ github.event.label.name == 'PR status: code ready' }}"
    timeout-minutes: 40
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.10
      - run: bun install -y
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
      - name: Setup OKTA Testing Environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TESTING_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Vercel CLI
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: bun add --global vercel@latest
      - name: Setup Canvas
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: npm rebuild canvas
      - uses: nrwl/nx-set-shas@v4
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - name: Get NX BASE and NX HEAD
        uses: nrwl/nx-set-shas@v4
      - name: Export NX BASE AND HEAD
        run: |
          export NX_BASE=${{ env.NX_BASE }}
          export NX_HEAD=${{ env.NX_HEAD }}
          export VERCEL_TOKEN=${{ env.VERCEL_TOKEN }}
          export GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}
          bash ./tools/scripts/export-action-env.sh
      - name: Run build on affected projects
        run: bunx nx build-affected-projects tools

  preview-and-E2E:
    runs-on: ubuntu-latest
    if: "${{ github.event.label.name == 'PR status: code ready' }}"
    timeout-minutes: 60
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      ACTION_TYPE: PULL_REQUEST_ACTION

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.10
      - run: bun install -y
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
      - name: Install Cypress
        run: bunx cypress install
      - name: Setup OKTA Testing Environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TESTING_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Vercel CLI
        if: "${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}"
        run: bun add --global vercel@latest
      - name: Get NX BASE and NX HEAD
        uses: nrwl/nx-set-shas@v4
      - name: Export NX BASE AND HEAD
        run: |
          export NX_BASE=${{ env.NX_BASE }}
          export NX_HEAD=${{ env.NX_HEAD }}
          export VERCEL_TOKEN=${{ env.VERCEL_TOKEN }}
          export GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}
          bash ./tools/scripts/export-action-env.sh
      - name: Generate Preview Links
        run: bunx nx preview-action tools